/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appforkids;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.Locale;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author DarknessYamii
 */
public class Piano extends javax.swing.JFrame {

    /**
     * Creates new form Piano
     */
    public Piano() {
        initComponents();
        confirm.setEnabled(false);
        ValidationGroup group = registroValidation.getValidationGroup();
        group.add(nameTxt, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(passwordTxt, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(edadTxt, StringValidators.REQUIRE_NON_EMPTY_STRING, StringValidators.REQUIRE_VALID_INTEGER);
        group.add(emailTxt, StringValidators.REQUIRE_NON_EMPTY_STRING, StringValidators.EMAIL_ADDRESS);
        group.add(telefonoTxt, StringValidators.REQUIRE_NON_EMPTY_STRING, StringValidators.REQUIRE_VALID_INTEGER);

        registroValidation.addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                if (registroValidation.getProblem() == null) {
                    confirm.setEnabled(true);
                } else {
                    confirm.setEnabled(false);
                }

            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroPanel = new javax.swing.JDialog();
        BK = new javax.swing.JPanel();
        registroValidation = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        ElementosForm = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        Edad = new javax.swing.JLabel();
        edadTxt = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        BackGroundPiano = new javax.swing.JPanel();
        topSide = new javax.swing.JPanel();
        Ludovico = new javax.swing.JButton();
        Faded = new javax.swing.JButton();
        GOT = new javax.swing.JButton();
        beethoven = new javax.swing.JButton();
        midSide = new javax.swing.JPanel();
        DO = new javax.swing.JButton();
        RE = new javax.swing.JButton();
        MI = new javax.swing.JButton();
        FA = new javax.swing.JButton();
        SOL = new javax.swing.JButton();
        LA = new javax.swing.JButton();
        SI = new javax.swing.JButton();
        DObajo = new javax.swing.JButton();
        botSide = new javax.swing.JPanel();
        Register = new javax.swing.JButton();
        footer = new javax.swing.JLabel();

        BK.setBackground(new java.awt.Color(255, 255, 255));

        ElementosForm.setBackground(new java.awt.Color(255, 255, 255));
        ElementosForm.setLayout(new java.awt.GridLayout(5, 0, 50, 0));

        Name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name.setText("Nombre:");
        ElementosForm.add(Name);

        nameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTxtFocusLost(evt);
            }
        });
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        ElementosForm.add(nameTxt);

        Password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Password.setText("Contraseña:");
        ElementosForm.add(Password);

        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTxtFocusLost(evt);
            }
        });
        ElementosForm.add(passwordTxt);

        Edad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Edad.setText("Edad:");
        ElementosForm.add(Edad);

        edadTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edadTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edadTxtFocusLost(evt);
            }
        });
        ElementosForm.add(edadTxt);

        Email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Email.setText("Email:");
        ElementosForm.add(Email);

        emailTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTxtFocusLost(evt);
            }
        });
        ElementosForm.add(emailTxt);

        Telefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Telefono.setText("Telefono: ");
        ElementosForm.add(Telefono);

        telefonoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoTxtFocusLost(evt);
            }
        });
        ElementosForm.add(telefonoTxt);

        confirm.setBackground(new java.awt.Color(204, 255, 255));
        confirm.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        confirm.setText("Confirmar");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BKLayout = new javax.swing.GroupLayout(BK);
        BK.setLayout(BKLayout);
        BKLayout.setHorizontalGroup(
            BKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BKLayout.createSequentialGroup()
                .addComponent(registroValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BKLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(BKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BKLayout.createSequentialGroup()
                        .addComponent(ElementosForm, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BKLayout.createSequentialGroup()
                        .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))))
        );
        BKLayout.setVerticalGroup(
            BKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BKLayout.createSequentialGroup()
                .addComponent(registroValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(ElementosForm, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout RegistroPanelLayout = new javax.swing.GroupLayout(RegistroPanel.getContentPane());
        RegistroPanel.getContentPane().setLayout(RegistroPanelLayout);
        RegistroPanelLayout.setHorizontalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RegistroPanelLayout.setVerticalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piano For Kids");

        BackGroundPiano.setBackground(new java.awt.Color(255, 255, 102));

        topSide.setBackground(new java.awt.Color(153, 153, 255));
        topSide.setLayout(new java.awt.GridLayout(1, 0));

        Ludovico.setBackground(new java.awt.Color(153, 153, 255));
        Ludovico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/piano (1).png"))); // NOI18N
        Ludovico.setBorder(null);
        Ludovico.setBorderPainted(false);
        Ludovico.setContentAreaFilled(false);
        Ludovico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LudovicoMouseClicked(evt);
            }
        });
        topSide.add(Ludovico);

        Faded.setBackground(new java.awt.Color(151, 151, 255));
        Faded.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/1606045942.jpg"))); // NOI18N
        Faded.setBorder(null);
        Faded.setBorderPainted(false);
        Faded.setContentAreaFilled(false);
        Faded.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FadedMouseClicked(evt);
            }
        });
        topSide.add(Faded);

        GOT.setBackground(new java.awt.Color(153, 153, 255));
        GOT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/256x256bb.jpg.png"))); // NOI18N
        GOT.setBorder(null);
        GOT.setBorderPainted(false);
        GOT.setContentAreaFilled(false);
        GOT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GOTMouseClicked(evt);
            }
        });
        topSide.add(GOT);

        beethoven.setBackground(new java.awt.Color(153, 153, 255));
        beethoven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/com-foofoo-baby-music-piano-kids-games-rhymes-songs (1).jpg"))); // NOI18N
        beethoven.setBorder(null);
        beethoven.setBorderPainted(false);
        beethoven.setContentAreaFilled(false);
        beethoven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beethovenMouseClicked(evt);
            }
        });
        topSide.add(beethoven);

        midSide.setBackground(new java.awt.Color(255, 255, 102));
        midSide.setLayout(new java.awt.GridLayout(1, 0));

        DO.setBackground(new java.awt.Color(255, 255, 102));
        DO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/iloveimg-resized/DO.png"))); // NOI18N
        DO.setToolTipText("");
        DO.setBorder(null);
        DO.setBorderPainted(false);
        DO.setContentAreaFilled(false);
        DO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOMouseClicked(evt);
            }
        });
        midSide.add(DO);

        RE.setBackground(new java.awt.Color(255, 255, 102));
        RE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/iloveimg-resized/RE.png"))); // NOI18N
        RE.setToolTipText("");
        RE.setBorder(null);
        RE.setBorderPainted(false);
        RE.setContentAreaFilled(false);
        RE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REMouseClicked(evt);
            }
        });
        midSide.add(RE);

        MI.setBackground(new java.awt.Color(255, 255, 102));
        MI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/iloveimg-resized/MI.png"))); // NOI18N
        MI.setToolTipText("");
        MI.setBorder(null);
        MI.setBorderPainted(false);
        MI.setContentAreaFilled(false);
        MI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MIMouseClicked(evt);
            }
        });
        midSide.add(MI);

        FA.setBackground(new java.awt.Color(255, 255, 102));
        FA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/iloveimg-resized/FA.png"))); // NOI18N
        FA.setToolTipText("");
        FA.setBorder(null);
        FA.setBorderPainted(false);
        FA.setContentAreaFilled(false);
        FA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FAMouseClicked(evt);
            }
        });
        midSide.add(FA);

        SOL.setBackground(new java.awt.Color(255, 255, 102));
        SOL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/iloveimg-resized/SO.png"))); // NOI18N
        SOL.setToolTipText("");
        SOL.setBorder(null);
        SOL.setBorderPainted(false);
        SOL.setContentAreaFilled(false);
        SOL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SOLMouseClicked(evt);
            }
        });
        midSide.add(SOL);

        LA.setBackground(new java.awt.Color(255, 255, 102));
        LA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/iloveimg-resized/LA.png"))); // NOI18N
        LA.setToolTipText("");
        LA.setBorder(null);
        LA.setBorderPainted(false);
        LA.setContentAreaFilled(false);
        LA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LAMouseClicked(evt);
            }
        });
        midSide.add(LA);

        SI.setBackground(new java.awt.Color(255, 255, 102));
        SI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/iloveimg-resized/SI.png"))); // NOI18N
        SI.setToolTipText("");
        SI.setBorder(null);
        SI.setBorderPainted(false);
        SI.setContentAreaFilled(false);
        SI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIMouseClicked(evt);
            }
        });
        midSide.add(SI);

        DObajo.setBackground(new java.awt.Color(255, 255, 102));
        DObajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appforkids/iloveimg-resized/DO.png"))); // NOI18N
        DObajo.setToolTipText("");
        DObajo.setBorder(null);
        DObajo.setBorderPainted(false);
        DObajo.setContentAreaFilled(false);
        DObajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DObajoMouseClicked(evt);
            }
        });
        midSide.add(DObajo);

        botSide.setBackground(new java.awt.Color(204, 0, 153));

        Register.setBackground(new java.awt.Color(204, 255, 255));
        Register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Register.setText("Registro");
        Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterMouseExited(evt);
            }
        });
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        botSide.add(Register);

        footer.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        footer.setForeground(new java.awt.Color(0, 0, 0));
        footer.setText("SELECCION DE ESCALA \"DO-RE-MI\"");
        botSide.add(footer);

        javax.swing.GroupLayout BackGroundPianoLayout = new javax.swing.GroupLayout(BackGroundPiano);
        BackGroundPiano.setLayout(BackGroundPianoLayout);
        BackGroundPianoLayout.setHorizontalGroup(
            BackGroundPianoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(midSide, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
            .addComponent(botSide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackGroundPianoLayout.setVerticalGroup(
            BackGroundPianoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundPianoLayout.createSequentialGroup()
                .addComponent(topSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 93, Short.MAX_VALUE)
                .addComponent(midSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(botSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPiano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPiano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOMouseClicked
        // TODO add your handling code here:

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\do.wav")));

            clip.start();

            Thread.sleep(clip.getMicrosecondLength() / 1000000);

        } catch (Exception e) {

        }

    }//GEN-LAST:event_DOMouseClicked

    private void MIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MIMouseClicked
        // TODO add your handling code here:

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\mi.wav")));

            clip.start();

            Thread.sleep(clip.getMicrosecondLength() / 1000000);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_MIMouseClicked

    private void REMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REMouseClicked
        // TODO add your handling code here:

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\re.wav")));

            clip.start();

            Thread.sleep(clip.getMicrosecondLength() / 1000000);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_REMouseClicked

    private void FAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FAMouseClicked
        // TODO add your handling code here:

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\fa.wav")));

            clip.start();

            Thread.sleep(clip.getMicrosecondLength() / 1000000);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_FAMouseClicked

    private void SOLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SOLMouseClicked
        // TODO add your handling code here:

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\sol.wav")));

            clip.start();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_SOLMouseClicked

    private void LAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAMouseClicked
        // TODO add your handling code here:

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\la.wav")));

            clip.start();

            Thread.sleep(clip.getMicrosecondLength() / 1000000);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_LAMouseClicked

    private void SIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIMouseClicked
        // TODO add your handling code here:

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\si.wav")));

            clip.start();

        } catch (Exception e) {

        }


    }//GEN-LAST:event_SIMouseClicked

    private void DObajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DObajoMouseClicked
        // TODO add your handling code here:

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\doBajo.wav")));

            clip.start();

            Thread.sleep(clip.getMicrosecondLength() / 1000000);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_DObajoMouseClicked

    private void LudovicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LudovicoMouseClicked
        // TODO add your handling code here:

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\loduvico.wav")));

            clip.start();

            Thread.sleep(clip.getMicrosecondLength() / 1000000);

        } catch (Exception e) {

        }

    }//GEN-LAST:event_LudovicoMouseClicked

    private void FadedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FadedMouseClicked
        // TODO add your handling code here:  

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\faded.wav")));

            clip.start();

            Thread.sleep(clip.getMicrosecondLength() / 1000000);

        } catch (Exception e) {

        }


    }//GEN-LAST:event_FadedMouseClicked

    private void GOTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTMouseClicked

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\got.wav")));

            clip.start();

            Thread.sleep(clip.getMicrosecondLength() / 1000000);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_GOTMouseClicked

    private void beethovenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beethovenMouseClicked

        try {

            Clip clip = AudioSystem.getClip();

            clip.open(AudioSystem.getAudioInputStream(new File("src\\music\\beet.wav")));

            clip.start();

            Thread.sleep(clip.getMicrosecondLength() / 1000000);

        } catch (Exception e) {

        }

    }//GEN-LAST:event_beethovenMouseClicked

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:

        RegistroPanel.setVisible(true);
        RegistroPanel.setSize(RegistroPanel.getMinimumSize());

    }//GEN-LAST:event_RegisterActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:

        RegistroPanel.setVisible(false);

    }//GEN-LAST:event_confirmActionPerformed

    private void RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseEntered
        Register.setForeground(Color.red);
        Register.setBackground(Color.green);
        Register.setSize(80, 30);

        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterMouseEntered

    private void RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseExited
        // TODO add your handling code here:

        Register.setForeground(Color.BLACK);
        Register.setBackground(Color.WHITE);
        Register.setSize(77, 25);

    }//GEN-LAST:event_RegisterMouseExited

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_nameTxtActionPerformed

    private void nameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFocusGained
        // TODO add your handling code here:

        Name.setForeground(Color.BLUE);
        Name.setFont(new Font("Segoe UI", Font.BOLD, 20));

    }//GEN-LAST:event_nameTxtFocusGained

    private void nameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFocusLost
        // TODO add your handling code here:

        Name.setForeground(Color.BLACK);
        Name.setFont(new Font("Segoe UI", Font.PLAIN, 18));
    }//GEN-LAST:event_nameTxtFocusLost

    private void passwordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusGained
        // TODO add your handling code here:

        Password.setForeground(Color.red);
        Password.setFont(new Font("Segoe UI", Font.BOLD, 20));
    }//GEN-LAST:event_passwordTxtFocusGained

    private void passwordTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusLost
        // TODO add your handling code here:

        Password.setForeground(Color.black);
        Password.setFont(new Font("Segoe UI", Font.PLAIN, 18));
    }//GEN-LAST:event_passwordTxtFocusLost

    private void edadTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edadTxtFocusGained
        // TODO add your handling code here:

        Edad.setForeground(Color.ORANGE);
        Edad.setFont(new Font("Segoe UI", Font.BOLD, 20));

    }//GEN-LAST:event_edadTxtFocusGained

    private void edadTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edadTxtFocusLost
        // TODO add your handling code here:
        Edad.setForeground(Color.BLACK);
        Edad.setFont(new Font("Segoe UI", Font.PLAIN, 18));
    }//GEN-LAST:event_edadTxtFocusLost

    private void emailTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFocusGained
        // TODO add your handling code here

        Email.setForeground(Color.pink);
        Email.setFont(new Font("Segoe UI", Font.BOLD, 20));

    }//GEN-LAST:event_emailTxtFocusGained

    private void emailTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFocusLost
        // TODO add your handling code here:
        Email.setForeground(Color.black);
        Email.setFont(new Font("Segoe UI", Font.PLAIN, 18));

    }//GEN-LAST:event_emailTxtFocusLost

    private void telefonoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTxtFocusGained
        // TODO add your handling code here:
        Telefono.setForeground(Color.magenta);

        Telefono.setFont(new Font("Segoe UI", Font.BOLD, 20));
    }//GEN-LAST:event_telefonoTxtFocusGained

    private void telefonoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTxtFocusLost
        // TODO add your handling code here:

        Telefono.setForeground(Color.black);

        Telefono.setFont(new Font("Segoe UI", Font.PLAIN, 18));
    }//GEN-LAST:event_telefonoTxtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Locale.setDefault(new Locale("es", "ES"));
                new Piano().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BK;
    private javax.swing.JPanel BackGroundPiano;
    private javax.swing.JButton DO;
    private javax.swing.JButton DObajo;
    private javax.swing.JLabel Edad;
    private javax.swing.JPanel ElementosForm;
    private javax.swing.JLabel Email;
    private javax.swing.JButton FA;
    private javax.swing.JButton Faded;
    private javax.swing.JButton GOT;
    private javax.swing.JButton LA;
    private javax.swing.JButton Ludovico;
    private javax.swing.JButton MI;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Password;
    private javax.swing.JButton RE;
    private javax.swing.JButton Register;
    private javax.swing.JDialog RegistroPanel;
    private javax.swing.JButton SI;
    private javax.swing.JButton SOL;
    private javax.swing.JLabel Telefono;
    private javax.swing.JButton beethoven;
    private javax.swing.JPanel botSide;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField edadTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel footer;
    private javax.swing.JPanel midSide;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField passwordTxt;
    private org.netbeans.validation.api.ui.swing.ValidationPanel registroValidation;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JPanel topSide;
    // End of variables declaration//GEN-END:variables
}
